name: social_network_share
description: A plugin for sharing contents to social media such as Facebook, Instargram, Twister
version: 0.0.3
homepage: https://github.com/a313/social_network_share

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.social_network_share
        pluginClass: SocialNetworkSharePlugin
      ios:
        pluginClass: SocialNetworkSharePlugin
